### ISSUE TITLE
Ping command output is dependant on system time 

### ISSUE THREAD

**Issue by Octol1ttle** [TeamOctolings/Boyfriend#29]
Latency for `!ping` is calculated by subtracting the remote "message delivered" timestamp from the current *local system* time. While this takes into account local computing time, this means that the output will be inaccurate if the system clock ever falls ahead/behind the Discord time.

**Comment by mctaylors** [comment]
how about using [API](http://worldtimeapi.org) instead of local time?

**Comment by Octol1ttle** [comment]
> how about using [API](http://worldtimeapi.org) instead of local time?

are Discord servers using the same API though?

**Comment by mctaylors** [comment]
> > how about using [API](http://worldtimeapi.org) instead of local time?
> 
> are Discord servers using the same API though?

idk, but i think you should try
