### ISSUE TITLE
Boyfriend can't kick bots

### ISSUE THREAD

**Issue by mctaylors** [TeamOctolings/Boyfriend#31]
i think this issue does not require a description

but there's a screenshot
![Screenshot_20230427-134137_Discord](https://user-images.githubusercontent.com/95250141/234840283-3824c39f-5c13-4ded-b9b0-a1fd6826ab9c.jpg)

**Comment by Octol1ttle** [comment]
Unable to reproduce, it appears that `SocketGuild#GetUser` returned `null` for whatever reason
