### ISSUE TITLE
Bot ignores some signs in the reminder

### ISSUE THREAD

**Issue by mctaylors** [TeamOctolings/Boyfriend#38]
have been spotted missing:
* `_` underscore 
* `*` asterisk
* `~` tilde
* `>` greather-than
* [ ` ] backtick

screenshot:

![image](https://github.com/TeamOctolings/Boyfriend/assets/95250141/d1620f3a-28a4-4463-92a3-a12bce5f7fa9)

possible solution: automatically add a backslash (`\`) after some characters

**Comment by Octol1ttle** [comment]
Issue caused by library (which is being replaced)
